<?php
$this->headTitle('View User');

$this->mainMenu()->setActiveItemId('users');

$this->pageBreadcrumbs()->setItems([
            'Home'=>$this->url('home'),
            'Manage Users'=>$this->url('users'),
            'View User'=>$this->url('users', ['action'=>'view', 'id'=>$user->getId()])
            ]);
?>

<?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>

<h1>View User <?= $this->escapeHtml($user->getEmail()) ?></h1>

<p>
    <a class="btn btn-default" href="<?= $this->url('users',
            ['action'=>'edit', 'id'=>$user->getId()]); ?>">
        <span class="glyphicon glyphicon-pencil" ></span> Edit
    </a>
    <a class="btn btn-default" href="<?= $this->url('users',
            ['action'=>'change-password', 'id'=>$user->getId()]); ?>">
        <span class="glyphicon glyphicon-asterisk"></span> Change Password
    </a>
</p>

<div class="row">
    <div class="col-md-6">
        <table class="table table-striped table-bordered">
             <tr>
                <th>ID:</th>
                <td><?= $this->escapeHtml($user->getId()) ?></td>
            </tr>
            <tr>
                <th>E-mail:</th>
                <td><?= $this->escapeHtml($user->getEmail()) ?></td>
            </tr>
            <tr>
                <th>Full Name:</th>
                <td><?= $this->escapeHtml($user->getFullName()) ?></td>
            </tr>
            <tr>
                <th>Date Created:</th>
                <td><?= $this->escapeHtml($user->getDateCreated()) ?></td>
            </tr>
            <tr>
                <th>Status:</th>
                <td><?= $this->escapeHtml($user->getStatusAsString()) ?></td>
            </tr>
            <tr>
                <th>Roles:</th>
                <td><?= $this->escapeHtml($user->getRolesAsString()) ?></td>
            </tr>
        </table>
    </div>
</div>