<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('OVOP')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

		<!-- Khmer fonts -->
		<link href='https://fonts.googleapis.com/css?family=Moul' rel='stylesheet' type='text/css'>
		<link href='https://fonts.googleapis.com/css?family=Freehand' rel='stylesheet' type='text/css'>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/ovop.png'])
                        ->prependStylesheet($this->basepath('highmaps/css/highcharts.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
                        ->prependStylesheet($this->basePath('css/style.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basepath('highmaps/countries/kh/kh-all.js'))
            ->prependFile($this->basepath('highmaps/js/highmaps.js'))
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-2.2.4.min.js'))
            ->prependFile($this->basepath('js/script.js'))
        ?>
    </head>
    <body class="body">
    	<div class="page-header">
    		<div class="container">
    			<div class="row">
            		<!-- Page header -->
					<div class="col-md-2 col-sm-2 text-center">
						<div class="img-responsive">
							<img class="moc-logo" alt="moc logo" src="<?= $this->basePath('/img/moc-logo.png'); ?>">
						</div>
					</div>
					<div class="col-md-8 col-sm-8 text-center">
						<h2 class="card">
        					<span class="card-kh">ក្រុមប្រឹក្សា​ស្ដារ​អភិវឌ្ឍន៍ ​វិស័យកសិកម្ម ​និង​ជនបទ</span><br>
        					<span class="card-en">Council for Agricultural and Rural Development</span>
        				</h2>
						<h3 class="ncovop">
        					<span class="ncovop-kh">គណៈកម្មា​ធិការ​ជាតិ​ ជំរុញចលនា ​ភូមិ១​ផលិតផល១</span><br>
        					<span class="ncovop-en">National Committee of One Village One Product Movement</span>
        				</h3>
					</div>
					<div class="col-md-2 col-sm-2 text-center">
						<div class="img-responsive">
							<img class="ovop-logo" alt="ovop logo" src="<?= $this->basePath('/img/ovop-logo.png');?>">
						</div>
					</div>
            	</div>
    		</div>
    	</div>
        <div class="page-body">
        	<div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <!-- Navigation bar -->
                        <?php
                        // Check if the activeMenuItemId passed to layout view model
                        // and if so, use it for setting active navbar item.
                        if (isset($activeMenuItemId)) {
                            $this->mainMenu()->setActiveItemId($activeMenuItemId);
                        }

                        // Render the navbar
                        echo $this->mainMenu()->render();
                        ?>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <!-- Breadcrumbs -->
                        <?= $this->pageBreadcrumbs()->render(); ?>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <!-- Page content placeholder -->
                        <?= $this->content; ?>
                    </div>
                </div>
                <hr>
            </div>
        </div>
        <div class="page-footer">
        	<div class="container">
        		<footer>
        			<div class="row">
        				<div class="col-md-12">
							<ul class="footer-top-link">
								<li><a href="<?= $this->url('about')?>" target="_blank">About</a></li>
								<li><a href="<?= $this->url('mission')?>" target="_blank">Mission</a></li>
								<li><a href="<?= $this->url('vision')?>" target="_blank">Vision</a></li>
								<li><a href="<?= $this->url('privacy')?>" target="_blank">Privacy</a></li>
								<li><a href="<?= $this->url('terms')?>" target="_blank">Terms</a></li>
								<li><a href="<?= $this->url('contact')?>" target="_blank">Contact</a></li>
								<li><a href="<?= $this->url('help')?>" target="_blank">Help</a></li>
							</ul>
        				</div>
        			</div>
        			<div class="row">
        				<div class="col-md-12">
        					Copyright &copy; <?= date('Y') ?> &nbsp; The One Village One Product Movement of Cambodia. All rights reserved.
        				</div>
        			</div>
                </footer>
        	</div>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
