<?php
$this->headTitle('Welcome');

$this->mainMenu()->setActiveItemId('home');

$this->pageBreadcrumbs()->setItems([
            'Home'=>$this->url('home')
            ]);
?>

<h1>Welcome</h1>

<p>
    to <b>o</b>ne <b>v</b>illage <b>o</b>ne <b>p</b>roduct movement of Cambodia (OVOP-Cambo).
    You'll find plenty of products of Cambodia which provided usefull information and services,
    plus user control by creating a free account. <br><br>
    Find out more on <a href="<?= $this->url('application', ['action'=>'setting'])?>">user policy.</a>
</p>
<br><br>
<p>
	<strong>Hint:</strong> not yet have an account, simply <a href="<?= $this->url('login', ['action'=>'login'])?>">create one</a>
	or use the following credentials to sign in by clicking the <em>Sign in</em> button at the top right.
    <ul>
        <li>Username: <em>jedipann@gmail.com</em></li>
        <li>Password: <em>password010</em></li>
    </ul>
</p>