<?php
$this->headTitle('Welcome');

$this->mainMenu()->setActiveItemId('home');

$this->pageBreadcrumbs()->setItems([
            'Home'=>$this->url('home')
            ]);
?>

<h1>Welcome</h1>

<p>
    This is the user role of ovop project application powered by Zend Framework 3.
    It is based on User RBAC, developed by Resolvo-dev.
    It demonstrates how to implement role-based access control.
</p>

<p>
	Click the <em>Sign in</em> button at the top right. To sign in, use the following credentials:
    <ul>
        <li>Username: <em>jedipann@gmail.com</em></li>
        <li>Password: <em>password010</em></li>
    </ul>
</p>